# Generated by Django 4.1.5 on 2023-11-19 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('usernote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
