# Generated by Django 4.1.5 on 2023-11-30 03:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_comment_id_alter_note_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=100, validators=[api.models.validate_comment_text]),
        ),
    ]
